name: Automated API Tests with Allure Reporting

on:
  push:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      # Login to Postman CLI using an API key
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-67ab07456e6a0100012d7965-99a44c2ad633b251c6b79c92fc8d824d20

      # Run the API Collection with Postman CLI
      - name: Run API tests with Postman CLI
        run: |
          postman collection run 39894904-66005209-c19c-4319-abd4-f4b9972dc5d7

      # Install Newman, Allure Reporter, and Allure Commandline
      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure
          npm install -g allure-commandline --save-dev

      # Run API tests and Generate Newman Allure Report
      - name: Run Newman and Generate Allure Report
        shell: bash
        run: |
          newman run https://api.getpostman.com/collections/39894904-66005209-c19c-4319-abd4-f4b9972dc5d7?apikey=PMAK-67ab07456e6a0100012d7965-99a44c2ad633b251c6b79c92fc8d824d20 \
          -r allure --reporter-allure-export allure-results

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # Create a unique folder name using a timestamp or a unique identifier
      - name: Create a unique directory for the report
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)  # Using timestamp for uniqueness
          mkdir "allure-report-$timestamp"
          mv allure-report "allure-report-$timestamp"  # Move report to the new folder

      # Deploy Allure Report to GitHub Pages with unique folder name
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: allure-report-$timestamp  # Use the unique folder
          publish_branch: gh-pages
          force_orphan: true

      # Send email with GitHub Pages link
      - name: Send email with Allure Report Link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          from: ${{ secrets.USERNAME }}
          to: mamunur.rashid@byslglobal.com
          subject: "Submission of Automated API Testing Report for Your Review"
          body: |
            Dear Sir,

            I hope this message finds you well.

            I am pleased to share that the API testing has been successfully completed, and the report has been generated using Allure Newman Reporter. 
            You may review the detailed findings at your convenience via the link below:

            https://mamun104.github.io/api-ci-cd-pipeline/allure-report-$timestamp/

            Kindly let me know if you have any feedback or require further clarification on any specific areas.

            Thank you for your time and consideration.

            Thanks and Best Regards
            ''''''''''''''''''''''''''''
            MD. Mamunur Rashid
            Sr. Executive, Software Quality Assurance
            Cloud Services Division
            Cell     : +880 1643946134
            E-Mail   : mamunur.rashid@byslglobal.com
            Web      : https://www.byslglobal.com/ 
