name: Automated API Tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest

    # Cache node_modules to speed up future runs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a stable version (adjust as necessary)

      # Cache node_modules folder to avoid re-installation on each run
      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      # Login to Postman CLI using an API key
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6790a5cd6e921600013db1e8-370cb0fafa0124fda923a8ce6b476c8e84

      # Run API tests with Postman CLI
      - name: Run API Tests using Postman CLI
        run: postman collection run 39894904-66005209-c19c-4319-abd4-f4b9972dc5d7

      # Install Newman and Newman Reporter (Only required dependencies)
      - name: Install Newman and Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      # Run API Tests using Newman (ensure the collection file exists)
      - name: Run API Tests using Newman
        run: newman run ./Collection/smartoffice.json -r htmlextra
