name: Automated API Tests for Specific Requests


on:
  push:
    branches:
      - main


jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3


      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"


      # Login to Postman CLI using an API key
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6790a5cd6e921600013db1e8-370cb0fafa0124fda923a8ce6b476c8e84


      # Run specific API requests with Postman CLI
      - name: Run Specific API Requests
        run: |
          # Specify tags or folders to filter and execute specific requests
          postman collection run 39894904-66005209-c19c-4319-abd4-f4b9972dc5d7 -i 39894904-720d08bb-1fb0-4634-a717-cc68d6dd59ec