name: Automated API Tests with Newman Reports

on:
  push:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Newman and htmlextra reporter
      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      # Download the collection using Postman API
      - name: Download Postman Collection
        env:
          POSTMAN_API_KEY: PMAK-679b6f001b20d100012ac69c-fd41a641750ce3d43725557729738df770
        run: |
          curl --location \
          --header "X-Api-Key: $POSTMAN_API_KEY" \
          https://api.getpostman.com/collections/16548351-891be621-9d54-4163-9b40-82023133d870 \
          --output collection.json

      # Run the API collection with Newman and generate htmlextra report
      - name: Run API Tests and Generate htmlextra Report
        run: |
          newman run collection.json \
          -r htmlextra \
          --reporter-htmlextra-export newman-report.html

      # Upload the Newman report as an artifact using v4
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-htmlextra-report
          path: newman-report.html
