name: Automated API Tests and Send Report

on:
  push:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Your API testing and Newman report generation steps go here

      # Upload the Newman report as an artifact
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-htmlextra-report
          path: newman-report.html

      # Send the report via Gmail
      - name: Send email with Newman Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          to: muhammadmamunurrashid340@gmail.com
          subject: "Automated API Test Report"
          body: |
            Please find the attached Newman htmlextra report for the latest API test run.
          attachments: newman-report.html